[versions]
kotlin = "2.0.20"
exposed = "0.53.0"
jjwt = "0.12.6"

[libraries]
exposed-spring-boot-starter = { module = "org.jetbrains.exposed:exposed-spring-boot-starter", version.ref = "exposed" }
exposed-java-time = { module = "org.jetbrains.exposed:exposed-java-time", version.ref = "exposed" }
jjwt-api = { module = "io.jsonwebtoken:jjwt-api", version.ref = "jjwt" }
jjwt-impl = { module = "io.jsonwebtoken:jjwt-impl", version.ref = "jjwt" }
jjwt-jackson = { module = "io.jsonwebtoken:jjwt-jackson", version.ref = "jjwt" }

[bundles]
exposed = ["exposed-spring-boot-starter", "exposed-java-time"]
jjwt = ["jjwt-api", "jjwt-impl", "jjwt-jackson"]
